name: Deploy React App
on: push 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v5
      - name: Install dependecies
        run: npm ci
      - name: Test Apllication 
        run: npm run test
      - name: Lint Apllication 
        run: npm run lint
      - name: Build Apllication 
        run: npm run build
      - name: Deploy 
        run: echo Deploying...
 